apiVersion: v1
kind: Pod
metadata:
  name: myapp-pod-version2
  labels:
    app: myapp
    appVersion: '2'
spec:
  containers:
  - name: myapp-container
    image: busybox
    command: ['sh', '-c', 'echo Hello Kubernetes! && sleep 3600']